# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14

# Mod Properties
mod_version=1.1.0
maven_group = com.github.TheRedBrain
archives_base_name=food-overhaul-vanilla-foods

# Dependencies
fabric_api_version=0.116.2+1.21.1
food_overhaul_version=2.3.0

fzzy_config_version=0.7.0+1.21
mana_attributes_version=2.6.0
stamina_attributes_version=2.6.0
health_regeneration_overhaul_version=2.4.1
overhauled_damage_version=2.2.1
resource_bar_api_version=2.6.2